# Generated by Django 3.2.7 on 2021-10-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='servicecode',
            field=models.CharField(max_length=25),
        ),
    ]
